name: Epipredict
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  meta: ^1.7.0
  dio: ^5.0.9
  logger: ^1.1.0
  shared_preferences: ^2.1.0
  intl: ^0.18.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0 # Correct package for launcher icons

# flutter_icons should be placed outside dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png" # Path to your app icon

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/app_icon.png
